// Code generated by go-bindata. DO NOT EDIT. @generated
// sources:
// templates/application/application.tmpl
// templates/index.tmpl
package templates

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesApplicationApplicationTmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\x51\x4d\x8b\x14\x31\x10\xbd\xef\xaf\xa8\xad\xf3\xb6\x61\x6e\x1e\x92\x06\x59\x17\x14\x04\x3d\x28\xea\xb1\x36\xa9\x9d\x94\x56\x27\x6d\x52\x3b\xcb\xb0\xcc\x7f\x97\x99\xee\x86\x11\x3c\xa5\x5e\xde\x47\xc2\x2b\x7f\xfb\xfe\xf3\xfd\xd7\x9f\x5f\x1e\x20\xdb\xa4\xe3\x8d\x3f\x1f\xa0\x54\xf6\x01\xb9\xe0\x78\x03\xe0\x33\x53\x3a\x0f\x00\x7e\x62\x23\x88\x99\x5a\x67\x0b\xf8\x6c\x4f\xc3\x5b\xbc\xa6\xb2\xd9\x3c\xf0\x9f\x67\x39\x04\xfc\x31\x7c\x7b\x37\xdc\xd7\x69\x26\x93\x47\x65\x84\x58\x8b\x71\xb1\x80\x1f\x1f\x02\xa7\x3d\xff\xe3\x2c\x34\x71\xc0\x83\xf0\xcb\x5c\x9b\x5d\x89\x5f\x24\x59\x0e\x89\x0f\x12\x79\xb8\x80\x3b\x90\x22\x26\xa4\x43\x8f\xa4\x1c\x76\x5b\x90\x89\x29\x8f\x9f\x78\x5f\x95\xba\x77\x0b\x5c\x28\x95\xf2\x1b\x72\xe3\xa7\x80\x8e\x7a\x67\xeb\x8e\xe6\x59\x25\x92\x49\x2d\x6f\x62\xef\x08\x13\x27\xa1\x80\xa4\x8a\xd0\x58\x03\x76\x3b\x2a\xf7\xcc\x6c\x08\x6e\x0d\xea\xb1\xc9\x6c\xd0\x5b\xfc\x7f\xd2\xaf\x8e\xa3\x77\x8b\xea\xd2\x9e\xdb\xea\xf3\x8f\x35\x1d\xd7\x94\xf3\x1d\xb7\x05\x9c\xe1\x6e\xf4\xb4\x7d\x0f\xc7\x0f\xac\x5a\xef\xe0\x7b\x6d\x9a\x6e\xbd\xa3\xd1\xbb\xbc\x5b\x9d\xee\xda\xea\x27\x92\xb2\x8c\xaf\xaf\x70\x14\xd6\x04\xa7\xd3\x2a\xdc\x38\xef\x96\x87\xbd\xbb\xac\xf8\x6f\x00\x00\x00\xff\xff\x80\x8d\x35\x6e\xf2\x01\x00\x00")

func templatesApplicationApplicationTmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesApplicationApplicationTmpl,
		"templates/application/application.tmpl",
	)
}

func templatesApplicationApplicationTmpl() (*asset, error) {
	bytes, err := templatesApplicationApplicationTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/application/application.tmpl", size: 498, mode: os.FileMode(420), modTime: time.Unix(1540424574, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templatesIndexTmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xb2\x29\xb0\xf3\x48\xcd\xc9\xc9\xd7\x51\x08\xcf\x2f\xca\x49\x51\xb4\xd1\x2f\xb0\x03\x04\x00\x00\xff\xff\xbb\x9e\x51\xad\x14\x00\x00\x00")

func templatesIndexTmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesIndexTmpl,
		"templates/index.tmpl",
	)
}

func templatesIndexTmpl() (*asset, error) {
	bytes, err := templatesIndexTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/index.tmpl", size: 20, mode: os.FileMode(420), modTime: time.Unix(1540424574, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/application/application.tmpl": templatesApplicationApplicationTmpl,
	"templates/index.tmpl": templatesIndexTmpl,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"templates": &bintree{nil, map[string]*bintree{
		"application": &bintree{nil, map[string]*bintree{
			"application.tmpl": &bintree{templatesApplicationApplicationTmpl, map[string]*bintree{}},
		}},
		"index.tmpl": &bintree{templatesIndexTmpl, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

